### ISSUE TITLE
TypeError: _serialize_list() got an unexpected keyword argument 'include_completed'

### ISSUE THREAD

**Issue by bjohas** [edtechhub/gtasks#9]
```
$ python3 ./gtasks backup
Backing up!
Including hidden tasks
Adding list to backup: My list
Traceback (most recent call last):
  File "./gtasks", line 107, in <module>
    main()
  File "./gtasks", line 89, in main
    args.func(args)
  File "./gtasks", line 98, in backup_hook
    backup(args.include)
  File "/home/.../backup.py", line 23, in backup
    content.append(_serialize_list(l, include_hidden=include_hidden, include_completed=include_hidden))
TypeError: _serialize_list() got an unexpected keyword argument 'include_completed'
```

**Comment by Resinderate** [comment]
Ah my mistake, this is fixed now on develop.
```
(gtasks) [16:50:03] ~/dev/gtasks (develop)
 λ ./gtasks backup
Backing up!
Including hidden tasks
Adding list to backup: My Tasks
Adding list to backup: Another List
Creating backup in file: backup-2019-11-25T16:50:51.490380.json
```
